# Generated by Django 3.1.6 on 2021-02-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0004_auto_20210211_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_category',
        ),
        migrations.AddField(
            model_name='activity',
            name='categories',
            field=models.ManyToManyField(to='gjorno.Category'),
        ),
    ]
