# Generated by Django 3.1.6 on 2021-02-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0008_auto_20210216_2325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
