# Generated by Django 3.1.6 on 2021-03-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0010_auto_20210223_1904'),
        ('gjorno', '0010_auto_20210224_1437'),
    ]

    operations = [
    ]
