# Generated by Django 3.1.6 on 2021-03-09 20:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gjorno', '0011_auto_20210225_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='max_participants',
            field=models.IntegerField(blank=True, default=None, help_text='For organization organized events. Maximum number of sign ups', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='user_member',
            field=models.ManyToManyField(blank=True, help_text='List of users that are members of organization', to=settings.AUTH_USER_MODEL),
        ),
    ]
