# Generated by Django 3.1.6 on 2021-03-09 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0012_auto_20210309_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='max_participants',
            field=models.IntegerField(blank=True, default=0, help_text='For organization organized events. Maximum number of sign ups', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
