# Generated by Django 3.1.6 on 2021-03-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gjorno', '0012_activity_signed_up'),
        ('gjorno', '0014_activity_activity_image'),
    ]

    operations = [
    ]
