export enum ActionTypes {
    EVENTS_FINISHED = "EVENTS_FINISHED",
    EVENTS_LOADING = "EVENTS_LOADING",
    EVENTS_ERROR = "EVENTS_ERROR",
    ORGS_FINISHED = "ORGS_FINISHED",
    ORGS_LOADING = "ORGS_LOADING",
    ORGS_ERROR = "ORGS_ERROR",
}
