export enum ActionTypes {
    EVENTS_FINISHED = "EVENTS_FINISHED",
    EVENTS_LOADING = "EVENTS_LOADING",
    EVENTS_ERROR = "EVENTS_ERROR",
    ORGS_FINISHED = "ORGS_FINISHED",
    ORGS_LOADING = "ORGS_LOADING",
    ORGS_ERROR = "ORGS_ERROR",
    GET_USER_FINISHED = "GET_USER_FINISHED",
    GET_USER_LOADING = "GET_USER_LOADING",
    GET_USER_ERROR = "GET_USER_ERROR",
    POST_USER_FINISHED = "POST_USER_FINISHED",
    POST_USER_LOADING = "POST_USER_LOADING",
    POST_USER_ERROR = "POST_USER_ERROR",
}
