export const eventTest = {
    id: 1,
    title: "test",
    date: "2021-06-06T20:20:20Z",
    organization_owner: 1,
    organization_owner_name: "org",
    user_owner: 1,
    user_owner_username: "user",
    description: "desc",
    location: "loc",
    categories_names: ["cat"],
    categories: [1],
    activity_level: 1,
    equipment_used: [1],
    equipment_used_names: ["eq"],
    max_participants: 1,
};
